### ISSUE TITLE
[Bare - task] Todo 추가하기

### ISSUE THREAD

**Issue by ekim49** [ekim49/todo-app-practice#1]
### 만들고자 하는 기능이 무엇인가요? (목적)
- Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요? (작업 상세 내용)
1. [ ] dummy data 를 사용해서 json-server 이용
2. [ ] Todo 를 list 로 구현 (view)
3. [ ] Todo 추가 하는 기능 구현

### 예상 작업 시간
- 3h

### 참고 사항
