### ISSUE TITLE
[Bare - task] Todo 삭제하기

### ISSUE THREAD

**Issue by ekim49** [ekim49/todo-app-practice#2]
### 만들고자 하는 기능이 무엇인가요?
- Todo 삭제 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 삭제하는 기능의 함수 만들기
2. [ ] Postman 에서 삭제가 성공적으로 되는지 확인
3. [ ] 브라우저에서 삭제가 성공적으로 되는지 확인

### 예상 작업 시간
- 3h
