### ISSUE TITLE
[Bare - task] Todo 수정하기

### ISSUE THREAD

**Issue by ekim49** [ekim49/todo-app-practice#3]
### 만들고자 하는 기능이 무엇인가요?
- Todo 수정 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 수정하는 기능의 함수 만들기
2. [ ] fetch로 put 요청하기
3. [ ] Postman 으로 수정이 잘 되는지 확인

### 예상 작업 시간
- 4h
