### ISSUE TITLE
[Advanced - task] Todo 전체 완료 버튼

### ISSUE THREAD

**Issue by ekim49** [ekim49/todo-app-practice#4]
### 만들고자 하는 기능이 무엇인가요?
- Todo 전체 완료 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [ ] 배열의 전체 data를 선택, 삭제하는 기능의 함수 만들기
2. [ ] fetch 로 delete 요청
3. [ ] Postman 으로 성공적으로 삭제 기능이 작동하는지 확인

### 예상 작업 시간
- 5h
